app = 'tensillabs-lite-frontend'
primary_region = 'iad'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[env]
  NODE_ENV = 'production'
  PORT = '3000'

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[deploy]
  release_command = 'npm run build'

[[mounts]]
  source = "next_cache"
  destination = "/.next/cache"
