version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - tensillabs

  app:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      PORT: 3000
      MONGODB_URI: mongodb://mongodb:27017/tensillabs-lite
    depends_on:
      - mongodb
    networks:
      - tensillabs
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mongodb_data:

networks:
  tensillabs:
    driver: bridge
