export const DATABASE_CONNECTION_NAME = 'Database';
export const IS_DEV = process.env.NODE_ENV !== 'production';
export const MONGODB_CONFIG = {
  CONNECTION_TIMEOUT: 30000,
  SERVER_SELECTION_TIMEOUT: 5000,
  HEARTBEAT_FREQUENCY: 10000,
  MAX_POOL_SIZE: 10,
  MIN_POOL_SIZE: 2,
  MAX_IDLE_TIME: 30000,
} as const;
